# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fd3ea6f7743c4ce019590b934a8a7957f28d9b2e28a667f7f4954d2e7b1f3de86f25c990fc446b530f6205a2408d9d38b979aaf112926f3e020461a8abbde22

test:
  secret_key_base: 6d2ef4d81ec0fd5636de6b60dbb27882dd87c03728ec25a5e72dc42d7972d68d2f9ecdfc1ada22acd7e03a52b72b2733322c3822a5cc023dcd9be5398d8b7fa8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
